### ISSUE TITLE
Communication API

### ISSUE THREAD

**Issue by wrestlerdude** [rynB2/group-project#6]
Calls to SQL Database

**Comment by wrestlerdude** [comment]
Following the top-down architecture diagram, the API will allow for simple function calls to execute SQL queries.
![image](https://raw.githubusercontent.com/rynB2/group-project/stable/Content/BlockchainApp%20Overview.svg)

**Comment by wrestlerdude** [comment]
Uses SQL databases

**Comment by DylanThomson33** [comment]
nodes push to sql database and query

**Comment by wrestlerdude** [comment]
Nodes no longer push to SQL database. Database is artificially filled.
